-- ============================================================================
-- Migration: 2163_authorization_seed_nav_tree.sql
-- Description:
--   Server-Side Authorization - Phase 1: the navigation bar hard-coded in
--   _Layout.cshtml, converted once into MenuMaster / PageMaster with the same
--   titles, icons, nesting and order, plus each page's VIEW endpoint mapping.
--   GENERATED from _Layout.cshtml by a parser - re-generate rather than hand-edit.
--
--   Conversion rules (blueprint "Moving the nav bar into the database"):
--     top-level entry           -> NAV (Home and IPD hold their single page)
--     dropdown-submenu toggle   -> MENU (SUBMENU if nested one level further)
--     item with controller/action -> PageMaster row, Show_In_Menu = 1, GET mapped to VIEW
--     divider                   -> a gap in Sort_Order (step 20 instead of 10)
--     disabled "#" placeholders -> skipped (they lead nowhere)
--   Counts: 8 nav items, 10 menus, 0 sub-menus, 139 menu pages.
--   Idempotent: every row is upserted by its code.
-- ============================================================================

USE [Dev_EMR];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_Auth_SeedNavTree
    @CompanyId INT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @page INT, @view INT;
    BEGIN TRANSACTION;
    DECLARE @m1 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'HOME', @Title=N'Home', @Icon=N'bi bi-house-fill me-1', @Sort_Order=10, @UserId=NULL, @Menu_ID=@m1 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m1, @Page_Code=N'HOME.DASHBOARD', @Title=N'Home', @Controller=N'Dashboard', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-house-fill me-1', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Dashboard', @Action=N'Index', @Source='SEED';
    DECLARE @m3 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'OPD', @Title=N'OPD', @Icon=N'bi bi-person-vcard me-2', @Sort_Order=20, @UserId=NULL, @Menu_ID=@m3 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.DASHBOARD', @Title=N'OPD Dashboard', @Controller=N'OPD', @Action=N'Dashboard', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-speedometer2 me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'Dashboard', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.DOCTORDASHBOARD', @Title=N'Doctor Dashboard', @Controller=N'OPD', @Action=N'DoctorDashboard', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-person-badge-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'DoctorDashboard', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.PATIENTREGISTRATION', @Title=N'Patient Registration', @Controller=N'OPD', @Action=N'PatientRegistration', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-person-plus-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'PatientRegistration', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.DOCTORROSTER', @Title=N'Doctor Roster', @Controller=N'DoctorRoster', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-calendar-range-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorRoster', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.SERVICEBOOKING', @Title=N'Service Booking', @Controller=N'OPD', @Action=N'ServiceBooking', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-calendar2-check-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'ServiceBooking', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.TOKENMANAGEMENT', @Title=N'Token Management', @Controller=N'OPD', @Action=N'TokenManagement', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-display me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'TokenManagement', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.VITALS', @Title=N'Patient Vitals', @Controller=N'Vitals', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-activity me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Vitals', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.DOCTORDISBURSAL', @Title=N'Doctor Commission & Disbursals', @Controller=N'DoctorDisbursal', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-wallet2 me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorDisbursal', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m3, @Page_Code=N'OPD.BILLCANCELLATION.OPD', @Title=N'Bill Cancellation & Refund', @Controller=N'BillCancellation', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=120, @Icon=N'bi bi-x-circle-fill me-2 text-danger', @Route_Values=N'moduleCode=OPD', @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'BillCancellation', @Action=N'Index', @Source='SEED';
    DECLARE @m13 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'LAB', @Title=N'LAB', @Icon=N'bi bi-droplet-half me-2', @Sort_Order=30, @UserId=NULL, @Menu_ID=@m13 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.LABDASHBOARD', @Title=N'LAB Dashboard', @Controller=N'LabDashboard', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-speedometer2 me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabDashboard', @Action=N'Index', @Source='SEED';
    DECLARE @m15 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m13, @Menu_Type='MENU', @Menu_Code=N'LAB.LAB_ORDER_BOOKING_REGISTRATION', @Title=N'LAB Order Booking / Registration', @Icon=N'bi bi-journal-plus me-2', @Sort_Order=20, @UserId=NULL, @Menu_ID=@m15 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2CBOOKING', @Title=N'B2C Booking / Registration', @Controller=N'LabOrderBooking', @Action=N'B2CBooking', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-person-fill-add me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2CBooking', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2CORDERLIST', @Title=N'B2C Order List', @Controller=N'LabOrderBooking', @Action=N'B2COrderList', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-journal-text me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2COrderList', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2BBOOKING', @Title=N'B2B Lab Billing & Booking', @Controller=N'LabOrderBooking', @Action=N'B2BBooking', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-building-fill-add me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2BBooking', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2BREGISTRATION', @Title=N'B2B Order List', @Controller=N'LabOrderBooking', @Action=N'B2BRegistration', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-journal-check me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2BRegistration', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2BINVOICES', @Title=N'B2B Invoices', @Controller=N'LabOrderBooking', @Action=N'B2BInvoices', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-file-earmark-medical me-2 text-info', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2BInvoices', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m15, @Page_Code=N'LAB.LABORDERBOOKING.B2BSETTLEMENT', @Title=N'B2B Multi-Bill Settlement', @Controller=N'LabOrderBooking', @Action=N'B2BSettlement', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-wallet2 me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrderBooking', @Action=N'B2BSettlement', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.SAMPLECOLLECTION', @Title=N'Sample Collection Management', @Controller=N'SampleCollection', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-eyedropper me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'SampleCollection', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.SAMPLETRANSFER', @Title=N'Sample Transfer', @Controller=N'SampleTransfer', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-arrow-left-right me-2 text-warning', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'SampleTransfer', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.LABREPORTING', @Title=N'Lab Reporting Entry', @Controller=N'LabReporting', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-file-earmark-medical me-2 text-info', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabReporting', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.LABIMAGEREPORTING', @Title=N'Image Report Entry', @Controller=N'LabImageReporting', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-file-earmark-image me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabImageReporting', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.LABREPORTDISPATCH', @Title=N'Lab Report Dispatch', @Controller=N'LabReportDispatch', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-printer-fill me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabReportDispatch', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.PATHOLOGISTDASHBOARD', @Title=N'Report Approval Dashboard', @Controller=N'PathologistDashboard', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-clipboard2-pulse-fill me-2 text-danger', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'PathologistDashboard', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.LABUNAPPROVE', @Title=N'Un-Authorize Report', @Controller=N'LabUnapprove', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-unlock-fill me-2 text-warning', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabUnapprove', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m13, @Page_Code=N'LAB.BILLCANCELLATION.LAB', @Title=N'Bill Cancellation & Refund', @Controller=N'BillCancellation', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=110, @Icon=N'bi bi-x-circle-fill me-2 text-danger', @Route_Values=N'moduleCode=LAB', @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'BillCancellation', @Action=N'Index', @Source='SEED';
    DECLARE @m30 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'IPD', @Title=N'IPD', @Icon=N'bi bi-hospital me-2', @Sort_Order=40, @UserId=NULL, @Menu_ID=@m30 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m30, @Page_Code=N'IPD.INDEX', @Title=N'IPD', @Controller=N'IPD', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-hospital me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'IPD', @Action=N'Index', @Source='SEED';
    DECLARE @m32 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'MASTER', @Title=N'Master', @Icon=N'bi bi-database-fill me-2', @Sort_Order=50, @UserId=NULL, @Menu_ID=@m32 OUTPUT;
    DECLARE @m33 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m32, @Menu_Type='MENU', @Menu_Code=N'MASTER.GENERAL', @Title=N'General', @Icon=N'bi bi-grid-fill me-2', @Sort_Order=10, @UserId=NULL, @Menu_ID=@m33 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.OPD', @Title=N'Patient Master', @Controller=N'OPD', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-person-heart me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OPD', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DOCTORS', @Title=N'Doctor Master', @Controller=N'Doctors', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-heart-pulse-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Doctors', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.REFERRALDOCTORS', @Title=N'Referral Doctor Master', @Controller=N'ReferralDoctors', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-person-lines-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'ReferralDoctors', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DOCTORSPECIALITIES', @Title=N'Doctor Speciality Master', @Controller=N'DoctorSpecialities', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-award-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSpecialities', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DOCTORSUBSPECIALITIES', @Title=N'Doctor Sub-Speciality Master', @Controller=N'DoctorSubSpecialities', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-patch-plus-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSubSpecialities', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DEPARTMENTS', @Title=N'Department Master', @Controller=N'Departments', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-building me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Departments', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.CLINICALUNITS', @Title=N'Clinical Unit Master', @Controller=N'ClinicalUnits', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-diagram-3-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'ClinicalUnits', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.CORPORATES', @Title=N'Corporate Master', @Controller=N'Corporates', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-briefcase-fill me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Corporates', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DISCOUNTTYPES', @Title=N'Discount Type Master', @Controller=N'DiscountTypes', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-tags-fill me-2 text-warning', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DiscountTypes', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.INSURANCES', @Title=N'Insurance / TPA Master', @Controller=N'Insurances', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-shield-check me-2 text-info', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Insurances', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.GOVERNMENTSCHEMES', @Title=N'Government Scheme Master', @Controller=N'GovernmentSchemes', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=110, @Icon=N'bi bi-bank2 me-2 text-warning', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'GovernmentSchemes', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.SHIFTS', @Title=N'Shift Master', @Controller=N'Shifts', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=120, @Icon=N'bi bi-clock-history me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Shifts', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.CONSENTMASTERS', @Title=N'Consent Masters', @Controller=N'ConsentMasters', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=130, @Icon=N'bi bi-file-earmark-check-fill me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'ConsentMasters', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.LABUNITS', @Title=N'Unit Master', @Controller=N'LabUnits', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=140, @Icon=N'bi bi-rulers me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabUnits', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.ANALYZERS', @Title=N'Analyzer Master', @Controller=N'Analyzers', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=150, @Icon=N'bi bi-cpu-fill me-2 text-info', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Analyzers', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.BUILDINGS', @Title=N'Building Master', @Controller=N'Buildings', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=160, @Icon=N'bi bi-buildings-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Buildings', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.FLOORS', @Title=N'Floor Master', @Controller=N'Floors', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=170, @Icon=N'bi bi-layers-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Floors', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.COUNTRIES', @Title=N'Country Master', @Controller=N'Countries', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=190, @Icon=N'bi bi-globe me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Countries', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.STATES', @Title=N'State Master', @Controller=N'States', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=200, @Icon=N'bi bi-map me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'States', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.DISTRICTS', @Title=N'District Master', @Controller=N'Districts', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=210, @Icon=N'bi bi-geo me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Districts', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.CITIES', @Title=N'City Master', @Controller=N'Cities', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=220, @Icon=N'bi bi-buildings me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Cities', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m33, @Page_Code=N'MASTER.AREAS', @Title=N'Area Master', @Controller=N'Areas', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=230, @Icon=N'bi bi-pin-map me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Areas', @Action=N'Index', @Source='SEED';
    DECLARE @m56 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m32, @Menu_Type='MENU', @Menu_Code=N'MASTER.OPD_MASTER', @Title=N'OPD Master', @Icon=N'bi bi-clipboard2-pulse me-2', @Sort_Order=20, @UserId=NULL, @Menu_ID=@m56 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.SERVICES', @Title=N'Service Master', @Controller=N'Services', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-clipboard2-check me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Services', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.DOCTORROOMS', @Title=N'Doctor Room', @Controller=N'DoctorRooms', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-door-open-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorRooms', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.ROOMDOCTORASSIGNMENT', @Title=N'Room Doctor Assignment', @Controller=N'RoomDoctorAssignment', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-person-lines-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'RoomDoctorAssignment', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.EMRINVESTIGATIONS', @Title=N'EMR Investigation Master', @Controller=N'EmrInvestigations', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-eyedropper me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'EmrInvestigations', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.EMRMEDICATIONS', @Title=N'EMR Medication Master', @Controller=N'EmrMedications', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-capsule me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'EmrMedications', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.DOCTORVISITPROCESSCONFIGS', @Title=N'Doctor Visit Process Config', @Controller=N'DoctorVisitProcessConfigs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-diagram-3-fill me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorVisitProcessConfigs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m56, @Page_Code=N'MASTER.DOCTORCOMMISSIONCONFIGS', @Title=N'Doctor Commission Config', @Controller=N'DoctorCommissionConfigs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-percent me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorCommissionConfigs', @Action=N'Index', @Source='SEED';
    DECLARE @m64 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m32, @Menu_Type='MENU', @Menu_Code=N'MASTER.IPD_MASTER', @Title=N'IPD Master', @Icon=N'bi bi-hospital me-2', @Sort_Order=30, @UserId=NULL, @Menu_ID=@m64 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.WARDS', @Title=N'Ward Master', @Controller=N'Wards', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-hospital me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Wards', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.NURSINGSTATIONS', @Title=N'Nursing Station Master', @Controller=N'NursingStations', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-person-workspace me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'NursingStations', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.ROOMS', @Title=N'IPD Room Master', @Controller=N'Rooms', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-door-open me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Rooms', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.BEDCATEGORIES', @Title=N'Bed Category Master', @Controller=N'BedCategories', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-bookmark-star me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'BedCategories', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.BEDS', @Title=N'Bed Master', @Controller=N'Beds', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-hospital-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Beds', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.TARIFFCATEGORIES', @Title=N'Tariff Category Master', @Controller=N'TariffCategories', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-tags-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'TariffCategories', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.BEDROOMTARIFFS', @Title=N'Bed/Room Tariff Master', @Controller=N'BedRoomTariffs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-receipt-cutoff me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'BedRoomTariffs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.HOSPITALSERVICES', @Title=N'Hospital Service Master', @Controller=N'HospitalServices', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-gear-wide-connected me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'HospitalServices', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.HOSPITALSERVICERATES', @Title=N'Hospital Service Rate Master', @Controller=N'HospitalServiceRates', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-cash-coin me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'HospitalServiceRates', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.PROCEDURES', @Title=N'Procedure Master', @Controller=N'Procedures', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=120, @Icon=N'bi bi-heart-pulse me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Procedures', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.PROCEDURETARIFFS', @Title=N'Procedure Tariff Master', @Controller=N'ProcedureTariffs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=130, @Icon=N'bi bi-receipt me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'ProcedureTariffs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.OTS', @Title=N'OT Master', @Controller=N'Ots', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=150, @Icon=N'bi bi-hospital me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Ots', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.OTEQUIPMENTS', @Title=N'OT Equipment Master', @Controller=N'OtEquipments', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=160, @Icon=N'bi bi-tools me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OtEquipments', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.OTTARIFFS', @Title=N'OT Tariff Master', @Controller=N'OtTariffs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=170, @Icon=N'bi bi-calculator me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'OtTariffs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.ANAESTHESIAS', @Title=N'Anaesthesia Master', @Controller=N'Anaesthesias', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=190, @Icon=N'bi bi-shield-plus me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Anaesthesias', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.ICUS', @Title=N'ICU Master', @Controller=N'Icus', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=210, @Icon=N'bi bi-hospital-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Icus', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.HOSPITALPACKAGES', @Title=N'Hospital Package Master', @Controller=N'HospitalPackages', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=230, @Icon=N'bi bi-box2-heart-fill me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'HospitalPackages', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m64, @Page_Code=N'MASTER.HOUSEKEEPING', @Title=N'Housekeeping Masters', @Controller=N'Housekeeping', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=250, @Icon=N'bi bi-brush-fill me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Housekeeping', @Action=N'Index', @Source='SEED';
    DECLARE @m83 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m32, @Menu_Type='MENU', @Menu_Code=N'MASTER.LAB_MASTER', @Title=N'Lab Master', @Icon=N'bi bi-eyedropper me-2', @Sort_Order=40, @UserId=NULL, @Menu_ID=@m83 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABTESTCATEGORIES', @Title=N'Test Category Master', @Controller=N'LabTestCategories', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-tags me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabTestCategories', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABTESTSUBCATEGORIES', @Title=N'Test Sub Category Master', @Controller=N'LabTestSubCategories', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-tag-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabTestSubCategories', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABSAMPLETYPES', @Title=N'Sample Type Master', @Controller=N'LabSampleTypes', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-droplet-half me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabSampleTypes', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABTESTMETHODS', @Title=N'Test Method Master', @Controller=N'LabTestMethods', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-gear-wide-connected me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabTestMethods', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LAB_MASTER.LABUNITS', @Title=N'Unit Master', @Controller=N'LabUnits', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-rulers me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabUnits', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABINVESTIGATIONS', @Title=N'Investigation Master', @Controller=N'LabInvestigations', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-journal-medical me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabInvestigations', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABINVESTIGATIONPROFILES', @Title=N'Investigation Profile Master', @Controller=N'LabInvestigationProfiles', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-collection-play me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabInvestigationProfiles', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABREFERENCERANGES', @Title=N'Reference Range Master', @Controller=N'LabReferenceRanges', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-sliders2-vertical me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabReferenceRanges', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABSAMPLEREJECTIONREASONS', @Title=N'Sample Rejection Reason Master', @Controller=N'LabSampleRejectionReasons', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-x-octagon me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabSampleRejectionReasons', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABREPORTINGCONDITIONS', @Title=N'Conditions of Reporting', @Controller=N'LabReportingConditions', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-file-earmark-ruled me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabReportingConditions', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABFRANCHISES', @Title=N'Franchise Setup', @Controller=N'LabFranchises', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=110, @Icon=N'bi bi-building-gear me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabFranchises', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABFRANCHISEBARCODES', @Title=N'Franchise Barcode Assignment', @Controller=N'LabFranchiseBarcodes', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=120, @Icon=N'bi bi-upc-scan me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabFranchiseBarcodes', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABRATELISTB2C', @Title=N'Rate List (B2C)', @Controller=N'LabRateListB2C', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=130, @Icon=N'bi bi-currency-dollar me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabRateListB2C', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABRATELISTFRANCHISE', @Title=N'Rate List (Franchise)', @Controller=N'LabRateListFranchise', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=140, @Icon=N'bi bi-building-gear me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabRateListFranchise', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABRATELISTCORPORATE', @Title=N'Rate List (Corporate)', @Controller=N'LabRateListCorporate', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=150, @Icon=N'bi bi-building me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabRateListCorporate', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABFORMULAPARAMETERS', @Title=N'Lab Formula Component', @Controller=N'LabFormulaParameters', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=160, @Icon=N'bi bi-calculator me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabFormulaParameters', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABDESCRIPTIVETESTTEMPLATES', @Title=N'Descriptive Test Template', @Controller=N'LabDescriptiveTestTemplates', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=170, @Icon=N'bi bi-file-earmark-richtext me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabDescriptiveTestTemplates', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABPARAMETEROPTIONS', @Title=N'Parameter Option Master', @Controller=N'LabParameterOptions', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=180, @Icon=N'bi bi-ui-radios me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabParameterOptions', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABORGANISMS', @Title=N'Organism Master', @Controller=N'LabOrganisms', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=190, @Icon=N'bi bi-bug me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabOrganisms', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABANTIBIOTICS', @Title=N'Antibiotic Master', @Controller=N'LabAntibiotics', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=200, @Icon=N'bi bi-capsule-pill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabAntibiotics', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABANTIBIOTICPANELS', @Title=N'Antibiotic Panel Master', @Controller=N'LabAntibioticPanels', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=210, @Icon=N'bi bi-grid-3x3-gap me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabAntibioticPanels', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABEXPERTRULES', @Title=N'Expert Rule Master', @Controller=N'LabExpertRules', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=220, @Icon=N'bi bi-shield-exclamation me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabExpertRules', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m83, @Page_Code=N'MASTER.LABBREAKPOINTS', @Title=N'Breakpoint Master', @Controller=N'LabBreakpoints', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=230, @Icon=N'bi bi-rulers me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabBreakpoints', @Action=N'Index', @Source='SEED';
    DECLARE @m107 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m32, @Menu_Type='MENU', @Menu_Code=N'MASTER.PHARMACY_MASTER', @Title=N'Pharmacy Master', @Icon=N'bi bi-bag-heart me-2', @Sort_Order=50, @UserId=NULL, @Menu_ID=@m107 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m107, @Page_Code=N'MASTER.MEDICINES', @Title=N'Medicine Master', @Controller=N'Medicines', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-capsule me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Medicines', @Action=N'Index', @Source='SEED';
    DECLARE @m109 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'SETTINGS', @Title=N'Settings', @Icon=N'bi bi-gear-fill me-2', @Sort_Order=60, @UserId=NULL, @Menu_ID=@m109 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.COMPANIES', @Title=N'Company Master', @Controller=N'Companies', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-buildings me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Companies', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.BRANCHES', @Title=N'Branch Master', @Controller=N'Branches', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-diagram-3 me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Branches', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.USERS', @Title=N'User Master', @Controller=N'Users', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-people me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Users', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.HOSPITALSETTINGS', @Title=N'Hospital Settings', @Controller=N'HospitalSettings', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-hospital-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'HospitalSettings', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.LABAPPROVALFLOWS', @Title=N'Pathologist Approval Flow', @Controller=N'LabApprovalFlows', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-diagram-3-fill me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'LabApprovalFlows', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.SMTPCONFIG', @Title=N'Email Configuration', @Controller=N'SmtpConfig', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-envelope-at me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'SmtpConfig', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.WHATSAPPCONFIG', @Title=N'WhatsApp Configuration', @Controller=N'WhatsAppConfig', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-whatsapp me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'WhatsAppConfig', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m109, @Page_Code=N'SETTINGS.VIDEOCONFIG', @Title=N'Video Consultation Config', @Controller=N'VideoConfig', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-camera-video-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'VideoConfig', @Action=N'Index', @Source='SEED';
    DECLARE @m118 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m109, @Menu_Type='MENU', @Menu_Code=N'SETTINGS.SECURITY', @Title=N'Security', @Icon=N'bi bi-shield-lock-fill me-2 text-danger', @Sort_Order=110, @UserId=NULL, @Menu_ID=@m118 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m118, @Page_Code=N'SETTINGS.SECURITY.MENUPAGES', @Title=N'Menu & Page Master', @Controller=N'Security', @Action=N'MenuPages', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-diagram-3-fill me-2 text-primary', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Security', @Action=N'MenuPages', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m118, @Page_Code=N'SETTINGS.SECURITY.ROLEPERMISSIONS', @Title=N'Role Permissions', @Controller=N'Security', @Action=N'RolePermissions', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-person-lock me-2 text-success', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Security', @Action=N'RolePermissions', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m118, @Page_Code=N'SETTINGS.SECURITY.USERPERMISSIONS', @Title=N'User Permissions', @Controller=N'Security', @Action=N'UserPermissions', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-person-gear me-2 text-warning', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Security', @Action=N'UserPermissions', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m118, @Page_Code=N'SETTINGS.SECURITY.EFFECTIVEPERMISSIONS', @Title=N'Effective Permissions', @Controller=N'Security', @Action=N'EffectivePermissions', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-search-heart me-2 text-info', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Security', @Action=N'EffectivePermissions', @Source='SEED';
    DECLARE @m123 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'UTILITY', @Title=N'Utility', @Icon=N'bi bi-tools me-2', @Sort_Order=70, @UserId=NULL, @Menu_ID=@m123 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m123, @Page_Code=N'UTILITY.AUDITLOGS', @Title=N'Audit Log', @Controller=N'AuditLogs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-journal-text me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'AuditLogs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m123, @Page_Code=N'UTILITY.EMAILLOGS', @Title=N'Email Logs', @Controller=N'EmailLogs', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-inbox-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'EmailLogs', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m123, @Page_Code=N'UTILITY.EMAILTEMPLATE', @Title=N'Email Templates', @Controller=N'EmailTemplate', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-envelope-paper me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'EmailTemplate', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m123, @Page_Code=N'UTILITY.EMRTEMPLATES', @Title=N'EMR Template Settings', @Controller=N'EmrTemplates', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-file-earmark-medical me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'EmrTemplates', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m123, @Page_Code=N'UTILITY.PATIENTPORTAL.LOGIN', @Title=N'Patient Login', @Controller=N'PatientPortal', @Action=N'Login', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-person-badge me-2', @Route_Values=NULL, @Link_Target=N'_blank', @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'PatientPortal', @Action=N'Login', @Source='SEED';
    DECLARE @m129 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=NULL, @Menu_Type='NAV', @Menu_Code=N'REPORTS', @Title=N'Reports', @Icon=N'bi bi-bar-chart-line-fill me-2', @Sort_Order=80, @UserId=NULL, @Menu_ID=@m129 OUTPUT;
    DECLARE @m130 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m129, @Menu_Type='MENU', @Menu_Code=N'REPORTS.LAB', @Title=N'LAB', @Icon=N'bi bi-droplet-half me-2', @Sort_Order=10, @UserId=NULL, @Menu_ID=@m130 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABBILLINGREGISTER', @Title=N'Daily Billing Register', @Controller=N'Reports', @Action=N'LabBillingRegister', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-journal-text me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabBillingRegister', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABB2CCOLLECTIONREGISTER', @Title=N'B2C Collection Register', @Controller=N'Reports', @Action=N'LabB2CCollectionRegister', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-receipt me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabB2CCollectionRegister', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABOUTSTANDINGDUES', @Title=N'Outstanding Dues & Ageing', @Controller=N'Reports', @Action=N'LabOutstandingDues', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-hourglass-split me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabOutstandingDues', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABDISCOUNTREGISTER', @Title=N'Discount Register', @Controller=N'Reports', @Action=N'LabDiscountRegister', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-percent me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabDiscountRegister', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABCANCELLATIONREFUND', @Title=N'Cancellation & Refund Register', @Controller=N'Reports', @Action=N'LabCancellationRefund', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-x-octagon me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabCancellationRefund', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABPATIENTORDERS', @Title=N'Patient-wise Lab Orders', @Controller=N'Reports', @Action=N'LabPatientOrders', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-person-lines-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabPatientOrders', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABB2BPARTNERBILLING', @Title=N'B2B Partner Billing Register', @Controller=N'Reports', @Action=N'LabB2BPartnerBilling', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-buildings me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabB2BPartnerBilling', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABFRANCHISEWALLET', @Title=N'Franchise Wallet Statement', @Controller=N'Reports', @Action=N'LabFranchiseWallet', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-wallet2 me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabFranchiseWallet', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m130, @Page_Code=N'REPORTS.LABB2BOUTSTANDING', @Title=N'B2B Outstanding & Credit Use', @Controller=N'Reports', @Action=N'LabB2BOutstanding', @Show_In_Menu=1, @Sort_Order=110, @Icon=N'bi bi-credit-card-2-back me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'LabB2BOutstanding', @Source='SEED';
    DECLARE @m140 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m129, @Menu_Type='MENU', @Menu_Code=N'REPORTS.OPD', @Title=N'OPD', @Icon=N'bi bi-file-medical me-2', @Sort_Order=20, @UserId=NULL, @Menu_ID=@m140 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m140, @Page_Code=N'REPORTS.DAILYCOLLECTION', @Title=N'Daily Collection', @Controller=N'Reports', @Action=N'DailyCollection', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-cash-stack me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'DailyCollection', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m140, @Page_Code=N'REPORTS.PATIENTREGISTER', @Title=N'Patient Register', @Controller=N'Reports', @Action=N'PatientRegister', @Show_In_Menu=1, @Sort_Order=20, @Icon=N'bi bi-people-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'PatientRegister', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m140, @Page_Code=N'REPORTS.OPDREPORT', @Title=N'Other OPD Report', @Controller=N'Reports', @Action=N'OPDReport', @Show_In_Menu=1, @Sort_Order=30, @Icon=NULL, @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'OPDReport', @Source='SEED';
    DECLARE @m144 INT;
    EXEC dbo.usp_Auth_MenuMaster_Upsert @CompanyId=@CompanyId, @Parent_Menu_ID=@m129, @Menu_Type='MENU', @Menu_Code=N'REPORTS.FINANCE_DOCTOR_SETTLEMENT', @Title=N'Finance / Doctor Settlement', @Icon=N'bi bi-cash-coin me-2', @Sort_Order=30, @UserId=NULL, @Menu_ID=@m144 OUTPUT;
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS', @Title=N'All Settlement Reports', @Controller=N'DoctorSettlementReports', @Action=N'Index', @Show_In_Menu=1, @Sort_Order=10, @Icon=N'bi bi-grid me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'Index', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.VISITPAYMENTSTATUS', @Title=N'RPT-01: Visit Payment Status', @Controller=N'DoctorSettlementReports', @Action=N'VisitPaymentStatus', @Show_In_Menu=1, @Sort_Order=30, @Icon=N'bi bi-clipboard2-check me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'VisitPaymentStatus', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.OUTSTANDINGBYVISIT', @Title=N'RPT-02: Outstanding by Visit', @Controller=N'DoctorSettlementReports', @Action=N'OutstandingByVisit', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-hourglass-split me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'OutstandingByVisit', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.DOCTORCOMMISSIONREPORT', @Title=N'RPT-03: Doctor Commission', @Controller=N'DoctorSettlementReports', @Action=N'DoctorCommissionReport', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-percent me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'DoctorCommissionReport', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.DISBURSALREGISTER', @Title=N'RPT-04: Disbursal Register', @Controller=N'DoctorSettlementReports', @Action=N'DisbursalRegister', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-journal-bookmark me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'DisbursalRegister', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.PAYMENTTRANSACTIONS', @Title=N'RPT-05: Payment Transactions', @Controller=N'DoctorSettlementReports', @Action=N'PaymentTransactions', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-credit-card-2-front me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'PaymentTransactions', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.BILLINGADJUSTMENTS', @Title=N'RPT-06: Billing Adjustments', @Controller=N'DoctorSettlementReports', @Action=N'BillingAdjustments', @Show_In_Menu=1, @Sort_Order=80, @Icon=N'bi bi-plus-slash-minus me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'BillingAdjustments', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.REFUNDREVERSALS', @Title=N'RPT-07: Refund & Reversal', @Controller=N'DoctorSettlementReports', @Action=N'RefundReversals', @Show_In_Menu=1, @Sort_Order=90, @Icon=N'bi bi-arrow-counterclockwise me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'RefundReversals', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m144, @Page_Code=N'REPORTS.DOCTORSETTLEMENTREPORTS.SETTLEMENTSUMMARY', @Title=N'RPT-08: Settlement Summary', @Controller=N'DoctorSettlementReports', @Action=N'SettlementSummary', @Show_In_Menu=1, @Sort_Order=100, @Icon=N'bi bi-pie-chart-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'DoctorSettlementReports', @Action=N'SettlementSummary', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m129, @Page_Code=N'REPORTS.IPDREPORT', @Title=N'IPD Report', @Controller=N'Reports', @Action=N'IPDReport', @Show_In_Menu=1, @Sort_Order=40, @Icon=N'bi bi-hospital me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'IPDReport', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m129, @Page_Code=N'REPORTS.PATIENTREPORT', @Title=N'Patient Report', @Controller=N'Reports', @Action=N'PatientReport', @Show_In_Menu=1, @Sort_Order=50, @Icon=N'bi bi-person-lines-fill me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'PatientReport', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m129, @Page_Code=N'REPORTS.BILLINGREPORT', @Title=N'Billing Report', @Controller=N'Reports', @Action=N'BillingReport', @Show_In_Menu=1, @Sort_Order=60, @Icon=N'bi bi-receipt me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'BillingReport', @Source='SEED';
    EXEC dbo.usp_Auth_PageMaster_Upsert @CompanyId=@CompanyId, @Menu_ID=@m129, @Page_Code=N'REPORTS.PHARMACYREPORT', @Title=N'Pharmacy Report', @Controller=N'Reports', @Action=N'PharmacyReport', @Show_In_Menu=1, @Sort_Order=70, @Icon=N'bi bi-capsule me-2', @Route_Values=NULL, @Link_Target=NULL, @UserId=NULL, @Page_ID=@page OUTPUT;
    SET @view = NULL; SELECT @view = Control_ID FROM dbo.PageControlMaster WHERE Page_ID = @page AND Control_Code = 'VIEW';
    EXEC dbo.usp_Auth_PageEndpointMap_Upsert @Page_ID=@page, @Control_ID=@view, @App='WEB', @Http_Method='GET', @Controller=N'Reports', @Action=N'PharmacyReport', @Source='SEED';

    COMMIT TRANSACTION;
END;
GO

DECLARE @co INT;
DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT CompanyId FROM dbo.CompanyMaster WHERE IsActive = 1;
OPEN c; FETCH NEXT FROM c INTO @co;
WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC dbo.usp_Auth_SeedNavTree @CompanyId = @co;
    FETCH NEXT FROM c INTO @co;
END
CLOSE c; DEALLOCATE c;
GO

PRINT 'Script 2163 applied: navigation tree seeded from _Layout.cshtml.';
GO
